### ISSUE TITLE
Expose code to level api

### ISSUE THREAD

**Issue by nobody5050** [craft-devs/craft-engine#21]
When defining levels we are able to define terrain features and starting player/mob positions. I move that we should also have an api for defining starting code. 

While this would introduce some inconsistencies, specifically in the mob spawning api (spawning mobs via the level api vs spawning them using api code run on level load) I think it would benefit both users of craft-engine and level designers overall.

For level designers it would allow them to hardcode mob ai, as well as set up block interactions. 

For end users it would allow easy modding, just load a level and modify its code. It would also let users gain more familiarity with the level’s they are playing without also compromising the original play style of craft.

**Comment by StealthHydra179** [comment]
I think this seems like a good idea and something that would be good to add.

**Comment by Alvarito050506** [comment]
Please see commit f689964, should it resolve this or is there anything left to do?

**Comment by nobody5050** [comment]
The commit is way too large for me to review in full. Does it build properly? If so I’d say create a pull for it.
